USE ZAFIRO_PRUEBA_BD;

CREATE TABLE `PRODUCTS`(
    `id` INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL,
	`created_at` DATETIME DEFAULT NULL,
	`updated_at` DATETIME DEFAULT NULL,
    `status` INT(255) NOT NULL,
	`category_id` INT(255) NOT NULL,
	FOREIGN KEY (`category_id`) REFERENCES `CATEGORY`(`id`)
);